firdekho_cart/cart/urls.py
from django.urls import path
from .views import (StoreView, CartView, OrderprocedeView,
                    CheckoutView, OrderRedirectView, CheckOutSinginView, CheckoutSingUpView)
from. import views
from django.contrib.auth.views import LoginView

app_name = "cart"


urlpatterns = [
    path('', StoreView.as_view(), name='store'),
    path('1/', views.test),
    path('create_or_add_to_cart/', views.create_or_add_to_cart, name="create_or_add_to_cart"),
    path('cart/', CartView.as_view(), name="cart"),
    path('updatepin/', views.update_pin, name="updatepin"),
    path('orderredirect/', OrderRedirectView.as_view(), name='order_redirect'),
    path('order_procede/', OrderprocedeView.as_view(), name="order_procede"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('checkoutsingup/', CheckoutSingUpView.as_view(), name="checkout_singup"),
    path('checkoutlogin/', CheckOutSinginView.as_view(), name="checkout_singin"),


]

firdekho_cart/firdekho_cart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('payment/', include('payment.urls', namespace='payment')),

]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

firdekho_cart/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from .manager import CartModelManager
from django.contrib.auth.models import AbstractUser
# from order.models import Order

# Create your models here.


class CustomUser(AbstractUser):
    state = models.CharField(max_length=240, null=True)
    city = models.CharField(max_length=240, null=True)
    pin = models.IntegerField(default=0, blank=False, null=True)
    seller = models.BooleanField(default=False)
    default_address = models.OneToOneField('order.Address',
                                           on_delete=models.CASCADE,
                                           related_name='defalut_add',
                                           null=True)

    def __str__(self):
        return self.username


class Product(models.Model):

    name = models.CharField(max_length=240)
    price = models.IntegerField(default=0, null=False)
    seller = models.ForeignKey(CustomUser, related_name="seller_pro",
                               on_delete=models.CASCADE, null=True)
    # order = models.ForeignKey('order.Order', on_delete=models.DO_NOTHING,
    #                           related_name="order_pro", null=True)

    def __str__(self):
        return self.name


class Cart(models.Model):

    owner = models.OneToOneField(CustomUser, null=True,
                                 blank=False, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    total_value = models.IntegerField(default=0, blank=True)
    total_item = models.IntegerField(default=0, null=True)
    shipping_local = models.IntegerField(default=0, null=True)
    shipping_regional = models.IntegerField(default=0, null=True)
    shipping_national = models.IntegerField(default=0, null=True)

    objects = CartModelManager()

firdekho_cart/cart/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.auth import login, authenticate
from . mixins import RequestKwargModelFormMixin
from .models import Cart
# from .views import get_user_pin


class SingUpForm(RequestKwargModelFormMixin, UserCreationForm):

                # def save(self):
                # 	print("upper")
                # return("suf")

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "username"]

    def _get_user_pin(self):
        '''
        output request user pin
        '''
        if self.request.user.is_authenticated:
            pin = self.request.user.pin
        else:
            pin = self.request.session.get("pin")
        return pin

    def save(self, commit=True):

        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.pin = self._get_user_pin()
            user.save()
            user_cart = Cart.objects.get_or_create_cart(self.request)
            # auth_user = authenticate(self.request, username=self.cleaned_data["username"],
            #                          password=self.cleaned_data["password1"])
            user_cart.owner = user
            login(self.request, user)
            user_cart.save()
        return user

firdekho_cart/cart/views.py
from django.shortcuts import render
from django.views.generic import ListView
from . models import Product, CustomUser
from django.shortcuts import HttpResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Cart
from django.contrib.auth import get_user_model
from django.db.models.signals import m2m_changed
from django.core.signals import request_started
from django.dispatch import receiver
from functools import reduce
from rest_framework.generics import UpdateAPIView
from django.conf import settings
import os
import pandas as pd
from random import randint
from django.db.models.signals import post_migrate
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from django.urls import reverse_lazy, reverse
from .forms import SingUpForm
from django.views.generic.edit import CreateView
from django.views.generic.base import RedirectView
from . mixins import RequestFormKwargsMixin


class StoreView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_cart = Cart.objects.get_or_create_cart(self.request)
        if user_cart:
            context['user_cart_products'] = user_cart.products.all()
            context.update(kwargs)
            return context
        else:
            return context


def test(request):
    cart = Cart.objects.get_or_create_cart(request)
    print(request.user)
    user_cart = Cart.objects.get_or_create_cart(request)
    print(user_cart)
    print(request.session.session_key)
    print(request.session.get("pin"))
    print(request.session.get("cart_id"))
    print(cart)
    return HttpResponse("i")


def get_cart(request):
    if request.user.is_authenticated:
        return Cart.objects.get_or_create_cart(request)
    else:
        return Cart.objects.get_or_create_cart(request)


@api_view(['POST'])
def create_or_add_to_cart(request):
    cart = Cart.objects.get_or_create_cart(request)
    product = Product.objects.get(name=request.data["product"])
    cart.products.add(product)
    return Response("added")


@api_view(['POST'])
def remove_from_cart(request):
    cart = Cart.objects.get_or_create_cart(request)
    product = Product.objects.get(name=request.data["product"])
    cart.products.remove
    (product)
    return Response("remove")


@receiver(m2m_changed, sender=Cart.products.through)
def cart_value_update(sender, instance, action, **kwargs):
    if action == "post_add" or action == "post_remove":
        instance.total_value = reduce(lambda price1, price2: price1 + price2,
                                      [pro.price for pro in instance.products.all()])
        instance.save()


def read_csv():
    '''
    read and modif csv return dataframe
    '''
    pincodes = os.path.join(settings.PROJECT_ROOT, 'pincodes.csv')
    df = pd.read_csv(pincodes)
    df['Pincode'] = df['Pincode'].fillna(0)
    return df


class CartView(ListView):
    template_name = 'cart.html'

    def get_queryset(self):
        cart = Cart.objects.get_or_create_cart(self.request)
        return cart.products.all()

    def _get_location(self, pin, df):
        '''
        Input product pin and DataFram.
        output Seller state & City
        '''
        loc = df.loc[df["Pincode"] == pin].iloc[0]
        return loc["State"], loc["City"]

    def _get_user_pin(self):
        '''
        output request user pin
        '''
        if self.request.user.is_authenticated:
            pin = self.request.user.pin
        else:
            pin = self.request.session.get("pin")
        return pin

    def _product_type(self, cart):
        '''
        output three list item. local contain products from same city.
        regional contain product from product from same state.
        national contain product out of the state
        '''
        local = []
        regional = []
        national = []
        df = read_csv()
        for f in cart.products.all():
            seller_state, seller_city = self._get_location(f.seller.pin, df)
            user_state, user_city = self._get_location(self._get_user_pin(), df)
            if user_city == seller_city:
                local.append(f)
                cart.shipping_local = 30
            elif user_state == seller_state:
                regional.append(f)
                cart.shipping_regional = 40
            else:
                national.append(f)
                cart.shipping_national = 50
            cart.save()
        return local, regional, national

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart.objects.get_or_create_cart(self.request)

        try:
            '''
            try catch can be remove if dataframecon if DataFram
            Pincode column doesn't contain NAN or 0
            '''
            self._product_type(cart)

        except IndexError:
            context['pin_error'] = True
        context['cart'] = cart
        context["pin"] = self._get_user_pin()
        context.update(kwargs)
        return context


@api_view(['POST'])
def update_pin(request):
    if request.user.is_authenticated:
        request.user.pin = int(request.data["pin"])
        request.user.save()
    else:
        request.session["pin"] = int(request.data["pin"])
    return Response("updated")


def create_seller():
    df = read_csv()
    row = df.iloc[randint(0, len(df.index))]
    for i in range(2):
        seller, created = CustomUser.objects.get_or_create(username="seller" + str(randint(1, 2000)),
                                                           first_name="sellername" + str(i),
                                                           seller=True, city=row["City"],
                                                           pin=row["Pincode"],
                                                           state=row["State"])

        product, created = Product.objects.get_or_create(name="product" + str(randint(1, 2000)),
                                                         price=randint(200, 5000),
                                                         seller=seller)


# @receiver(post_migrate, sender=self)
# @receiver(request_started)
def create_init_db(sender, **kwars):
    ''' 
    reciver function 
    populate database with 2 seller and 2 product of each seller
    '''
    create_seller()


class OrderprocedeView(LoginView):

    template_name = 'order_procede.html'


class CheckoutView(ListView):
    template_name = "checkout.html"

    def get_queryset(self):
        return Product.objects.all()


class SingUpView(CreateView):
    '''
    main singup View
    '''
    template_name = 'usercreation.html'
    form_class = SingUpForm
    success_url = reverse_lazy('cart:store')


class CheckoutSingUpView(RequestFormKwargsMixin, SingUpView):
    '''
    checkout singup view
    add the existing cart to created user.

    '''
    success_url = reverse_lazy('order:address')


class CheckOutSinginView(LoginView):
    template_name = "login.html"
    # success_url = reverse_lazy('cart:store')

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or reverse_lazy('order:address')


class OrderRedirectView(RedirectView):
    '''
    redirect Authticated user to chackeout page.
    redirect Anonymous user to singup page

    '''

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            url = reverse('order:address')
        else:
            url = reverse('cart:checkout_singup')
        return url

firdekho_cart/cart/templates/cart.html
{% extends "core.html" %}
{% block title %}
<title>Cart</title>
{% endblock %}

{% block body %}
<div class="container">
	<h5>My Cart</h5>
	<div class="row">
			<div class="col-7">
				{% if object_list %}
					{% for pro in object_list %}
						<div class="card" style="width: 18rem;">
  						<img src="..." class="card-img-top" alt="...">
						  <div class="card-body">
						    <h5 class="card-title">{{ pro.name }}</h5>
						    <div class="card-text">
						    	<div>MRP - {{ pro.mrp }}</div>
						    	<div>{{ pro.seller }}</div>
						    	<div>Selling - {{ pro.price }}</div>
						    </div>
						    <a href={% url 'cart:cart' %} class="btn btn-primary">Remove</a>
						  </div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
			<div class="col-2">
				<h4>pin</h4>
				<input type="text" id="pin" value="{{pin}}">
				{% if pin_error %}
					<h4>enter correnct pin</h4>

				{% endif %}
				<h5>Price details</h5>
				{% if cart%}
					<div>{{cart.total_value}}</div>
				{% endif %}
				<h5>local shipping charge</h5> -  <span>{{cart.shipping_local}}</span>
				<h5>regional shipping charge</h5> -  <span>{{cart.shipping_regional}}</span>
				<h5>national shipping charge</h5> -  <span>{{cart.shipping_national}}</span>
				<hr>

				<a class="btn btn-primary" href="{% url 'cart:order_redirect' %}"  
				role="button">
				Order Now
				</a>

	</div>
	</div>
</div>
{% endblock %}

{% block script %}
	<script>
	$('#pin').focusout(function(e){
		var pin = e.target.value;
		$.ajax({
    url: "http://127.0.0.1:8000/updatepin/",
    type: "POST",
    data: {
    	pin: pin,
    	csrfmiddlewaretoken: "{{ csrf_token }}",
    },
    success: function(){
    }
    })
	})
	</script>
{% endblock %}

firdekho_cart/cart/templates/checkout.html
{% extends 'core.html' %}

{% block body %}


{% endblock %}

firdekho_cart/cart/templates/core.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    {% block title %} <title></title> {% endblock %}
  </head>
  <body>
    {% block body %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block script %} {% endblock %}
  </body>
</html>

firdekho_cart/cart/templates/index.html
{% extends 'core.html' %}
{% block title %} <title>Store</title>{% endblock %}
{% block body %}
<div class="container">
	<!-- Image and text -->
	<nav class="navbar navbar-sucess bg-secondary">
	  <a class="navbar-brand" href="{% url 'cart:cart' %}">
	    <i class="fas fa-shopping-cart"></i>
	    Cart
	  </a>
	</nav>
		<div>
		{% if object_list %}
			{% for pro in object_list %}
				<div class="card" style="width: 18rem;">
  				<img src="" class="card-img-top">
  				<div class="card-body">
    				<h5 class="card-title">{{pro.name}}</h5>
    				<p class="card-text">{{pro.description}}</p>
    				<div class="btn " style="padding:0">
    					{% if pro in user_cart_products %}
    						<button class=" add-button">Added To Cart</button>
    					{% else %}
    						<button class=" add-button">Add To Cart</button>
    					{% endif %}

    				</div>
  				</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
{% endblock %}


{% block script %}

  <!-- Load React. -->
  <!-- Note: when deploying, replace "development.js" with "production.min.js". -->
  <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin>
  </script>

  <!-- Load our React component. -->
  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
  <script>
		$(".add-button").click(function(e){
			var addurl = "http://127.0.0.1:8000/create_or_add_to_cart/";
			console.log("working")
			// console.log($(e.target).parent().siblings("h5").text())
			var product = $(e.target).parent().siblings("h5").text()
			$(e.target).replaceWith(
				// "<button class='dec-pro'>-</button>" +
				// "	<input value=1 style={padding:3px 6px, display:inline-block}>"+
				"<button>Added To Cart</button>");
			$.ajax({
       url: addurl ,
       dataType: "json",
       type: "POST",
       data:{
        product: product ,
        csrfmiddlewaretoken: "{{ csrf_token }}",
       },
       success: function(data){
        console.log(data)
       }
     });
		})
		
	</script>
{% endblock %}

firdekho_cart/cart/templates/login.html
{% extends 'core.html' %}

{% block body %}
<div>
	<form method="post">{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Login</button>
	</form>

</div>
{% endblock %}

firdekho_cart/cart/templates/order_procede.html
{% extends 'core.html' %}

{% block body %}

<form action="" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-primary" type="submit">Login</button>

</form>
<div> <a class="btn btn-primary" href="{% url 'cart:singup' %}" role="button">Sing Up</a></div>

{% endblock %}

firdekho_cart/cart/templates/usercreation.html
{% extends 'core.html' %}


{% block body %}
<form action="" method="post">{% csrf_token %}
	{{form.as_p}}
	<button type="submit" >singup</button>
	
</form>
<button><a href="{% url 'cart:checkout_singin' %}">singin</a></button>
{% endblock %}